style = Style.create([{ key: 'cultural history', 
                        text: 'cultural history', 
                        value: 'cultural history', 
                        feature: 'historical, quaint'}, 
                     { key: 'snow scene', 
                        text: 'snow scene', 
                        value: 'snow scene', 
                        feature: 'pure, romantic, remind of Christmas'},
                     { key: 'starry sky', 
                        text: 'starry sky', 
                        value: 'starry sky', 
                        feature: 'blinking stars, quiet and peaceful'},
                     { key: 'sea of flowers', 
                        text: 'sea of flowers', 
                        value: 'sea of flowers', 
                        feature: 'floral, colorful' },
                     { key: 'mountain', 
                        text: 'mountain', 
                        value: 'mountain', 
                        feature: 'the beauty of the landscape, splendid'},
                     { key: 'aurora', 
                        text: 'aurora', 
                        value: 'aurora', 
                        feature: 'grand, spectacular'},
                     { key: 'beach', 
                        text: 'beach', 
                        value: 'beach', 
                        feature: 'relaxed, beautiful' },
                     { key: 'prairies', 
                        text: 'prairies', 
                        value: 'prairies', 
                        feature: 'vast, extensive'}
                    ])

season = Season.create([{ key: 'January',
                           text: 'January',
                           value: 'January'}, 
                        { key: 'February',
                           text: 'February',
                           value: 'February'},
                        { key: 'March',
                           text: 'March',
                           value: 'March' },
                        { key: 'April',
                           text: 'April',
                           value: 'April' },
                        { key: 'May',
                           text: 'May',
                           value: 'May'},
                        { key: 'June',
                           text: 'June',
                           value: 'June'},
                        { key: 'July',
                           text: 'July',
                           value: 'July' },
                        { key: 'August',
                           text: 'August',
                           value: 'August'},
                        { key: 'September',
                           text: 'September',
                           value: 'September'},
                        { key: 'October',
                           text: 'October',
                           value: 'October'},
                        { key: 'November',
                           text: 'November',
                           value: 'November'},
                        { key: 'December',
                           text: 'December',
                           value: 'December' }
                        ])

